//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Field_of_Wonders.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Field_of_Wonders.Localization.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ответ не может быть пустым..
        /// </summary>
        public static string Error_AnswerCannotBeEmpty {
            get {
                return ResourceManager.GetString("Error_AnswerCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбранный язык &apos;{0}&apos; не найден ({1}).\nБудет использован язык по умолчанию..
        /// </summary>
        public static string Error_ApplyCulture_NotFound_Format {
            get {
                return ResourceManager.GetString("Error_ApplyCulture_NotFound_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка установки языка.
        /// </summary>
        public static string Error_ApplyCulture_Title {
            get {
                return ResourceManager.GetString("Error_ApplyCulture_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла непредвиденная ошибка при установке языка:\n{0}.
        /// </summary>
        public static string Error_ApplyCulture_Unexpected_Format {
            get {
                return ResourceManager.GetString("Error_ApplyCulture_Unexpected_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Критическая ошибка: Не удалось установить ни один из доступных языков. Приложение будет закрыто..
        /// </summary>
        public static string Error_Critical_CannotSetAnyLanguage {
            get {
                return ResourceManager.GetString("Error_Critical_CannotSetAnyLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось обнаружить поддерживаемые языки. Приложение будет закрыто..
        /// </summary>
        public static string Error_Critical_NoLanguagesFound {
            get {
                return ResourceManager.GetString("Error_Critical_NoLanguagesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Критическая ошибка.
        /// </summary>
        public static string Error_Critical_Title {
            get {
                return ResourceManager.GetString("Error_Critical_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка инициализации данных игры:\n{0}.
        /// </summary>
        public static string Error_DataInitializationFailed_Format {
            get {
                return ResourceManager.GetString("Error_DataInitializationFailed_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла ошибка при автоматическом определении языков:\n{0}\n\nБудет использован язык по умолчанию..
        /// </summary>
        public static string Error_DiscoverLanguages_Failed_Format {
            get {
                return ResourceManager.GetString("Error_DiscoverLanguages_Failed_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка определения языков.
        /// </summary>
        public static string Error_DiscoverLanguages_Title {
            get {
                return ResourceManager.GetString("Error_DiscoverLanguages_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необработанное исключение UI: {0}.
        /// </summary>
        public static string Error_DispatcherUnhandledException_Format {
            get {
                return ResourceManager.GetString("Error_DispatcherUnhandledException_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка чтения файла настроек &apos;{0}&apos;:\n{1}\n\nПроверьте права доступа к папке приложения..
        /// </summary>
        public static string Error_LoadSettings_IOException_Format {
            get {
                return ResourceManager.GetString("Error_LoadSettings_IOException_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при чтении файла настроек &apos;{0}&apos;:\n{1}\n\nФайл будет удален. При следующем запуске потребуется выбрать язык..
        /// </summary>
        public static string Error_LoadSettings_ReadFailed_Format {
            get {
                return ResourceManager.GetString("Error_LoadSettings_ReadFailed_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка загрузки настроек.
        /// </summary>
        public static string Error_LoadSettings_Title {
            get {
                return ResourceManager.GetString("Error_LoadSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Непредвиденная ошибка при загрузке настроек из &apos;{0}&apos;:\n{1}\n\nФайл будет удален. При следующем запуске потребуется выбрать язык..
        /// </summary>
        public static string Error_LoadSettings_Unexpected_Format {
            get {
                return ResourceManager.GetString("Error_LoadSettings_Unexpected_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вопрос не может быть пустым..
        /// </summary>
        public static string Error_QuestionCannotBeEmpty {
            get {
                return ResourceManager.GetString("Error_QuestionCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось сохранить настройки.\nНе удалось определить директорию для файла настроек: {0}.
        /// </summary>
        public static string Error_SaveSettings_DirectoryNotFound_Format {
            get {
                return ResourceManager.GetString("Error_SaveSettings_DirectoryNotFound_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла ошибка при записи файла настроек &apos;{0}&apos;:\n{1}.
        /// </summary>
        public static string Error_SaveSettings_IOException_Format {
            get {
                return ResourceManager.GetString("Error_SaveSettings_IOException_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка сохранения настроек.
        /// </summary>
        public static string Error_SaveSettings_Title {
            get {
                return ResourceManager.GetString("Error_SaveSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось сохранить настройки.\nОтказано в доступе к файлу:\n{0}\n\nПроверьте права на запись..
        /// </summary>
        public static string Error_SaveSettings_Unauthorized_Format {
            get {
                return ResourceManager.GetString("Error_SaveSettings_Unauthorized_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла непредвиденная ошибка при сохранении настроек:\n{0}.
        /// </summary>
        public static string Error_SaveSettings_Unexpected_Format {
            get {
                return ResourceManager.GetString("Error_SaveSettings_Unexpected_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Непредвиденная ошибка при инициализации игры:\n{0}.
        /// </summary>
        public static string Error_UnexpectedInitializationFailed_Format {
            get {
                return ResourceManager.GetString("Error_UnexpectedInitializationFailed_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необработанное исключение: {0}.
        /// </summary>
        public static string Error_UnhandledException_Format {
            get {
                return ResourceManager.GetString("Error_UnhandledException_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Критическая ошибка. Необработанное исключение, детали недоступны..
        /// </summary>
        public static string Error_UnhandledException_NoExceptionObject {
            get {
                return ResourceManager.GetString("Error_UnhandledException_NoExceptionObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ru-RU.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Культура &apos;{0}&apos; добавлена в список..
        /// </summary>
        public static string Log_AddedCultureToList {
            get {
                return ResourceManager.GetString("Log_AddedCultureToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавлен резервный язык: {0}..
        /// </summary>
        public static string Log_AddedFallbackLanguage {
            get {
                return ResourceManager.GetString("Log_AddedFallbackLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось добавить резервные языки, кроме жестко заданного ru-RU..
        /// </summary>
        public static string Log_AddedHardcodedFallback {
            get {
                return ResourceManager.GetString("Log_AddedHardcodedFallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Application.Current был null. Невозможно выполнить корректное завершение..
        /// </summary>
        public static string Log_AppCurrentNull {
            get {
                return ResourceManager.GetString("Log_AppCurrentNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завершение работы приложения с кодом {0}..
        /// </summary>
        public static string Log_AppExiting {
            get {
                return ResourceManager.GetString("Log_AppExiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Культура &quot;{0}&quot; не найдена: {1}.
        /// </summary>
        public static string Log_ApplyCulture_NotFound_Format {
            get {
                return ResourceManager.GetString("Log_ApplyCulture_NotFound_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Непредвиденная ошибка при применении культуры: {0}.
        /// </summary>
        public static string Log_ApplyCulture_Unexpected_Format {
            get {
                return ResourceManager.GetString("Log_ApplyCulture_Unexpected_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка применения культуры: {0}.
        /// </summary>
        public static string Log_ApplyingCulture_Attempt {
            get {
                return ResourceManager.GetString("Log_ApplyingCulture_Attempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Непредвиденная ошибка при применении культуры {0}..
        /// </summary>
        public static string Log_ApplyingCulture_Failed {
            get {
                return ResourceManager.GetString("Log_ApplyingCulture_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось применить выбранную/сохраненную культуру: {0}. Попытка использовать резервную..
        /// </summary>
        public static string Log_ApplyingCulture_Fallback {
            get {
                return ResourceManager.GetString("Log_ApplyingCulture_Fallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Успешно применена резервная культура: {0}.
        /// </summary>
        public static string Log_ApplyingCulture_FallbackSuccess {
            get {
                return ResourceManager.GetString("Log_ApplyingCulture_FallbackSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Культура &apos;{0}&apos; не найдена. Применение невозможно..
        /// </summary>
        public static string Log_ApplyingCulture_NotFound {
            get {
                return ResourceManager.GetString("Log_ApplyingCulture_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Культура {0} успешно применена к текущему потоку..
        /// </summary>
        public static string Log_ApplyingCulture_Success {
            get {
                return ResourceManager.GetString("Log_ApplyingCulture_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запуск приложения. Инициализация службы логирования..
        /// </summary>
        public static string Log_AppStarting {
            get {
                return ResourceManager.GetString("Log_AppStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Базовая директория &apos;{0}&apos; не существует. Сканирование сателлитных сборок невозможно..
        /// </summary>
        public static string Log_BaseDirectoryNotExist {
            get {
                return ResourceManager.GetString("Log_BaseDirectoryNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Критическая ошибка: {0}.
        /// </summary>
        public static string Log_CriticalError {
            get {
                return ResourceManager.GetString("Log_CriticalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Культура &quot;{0}&quot; добавлена в список поддерживаемых языков..
        /// </summary>
        public static string Log_CultureAddedToList {
            get {
                return ResourceManager.GetString("Log_CultureAddedToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка добавить культуру &apos;{0}&apos;, но она не найдена..
        /// </summary>
        public static string Log_CultureAddNotFound {
            get {
                return ResourceManager.GetString("Log_CultureAddNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Культура &quot;{0}&quot; успешно применена..
        /// </summary>
        public static string Log_CultureApplied {
            get {
                return ResourceManager.GetString("Log_CultureApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код культуры &apos;{0}&apos; недействителен..
        /// </summary>
        public static string Log_CultureInvalid {
            get {
                return ResourceManager.GetString("Log_CultureInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обнаружение поддерживаемых языков....
        /// </summary>
        public static string Log_DiscoveringLanguages {
            get {
                return ResourceManager.GetString("Log_DiscoveringLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось обнаружить языки: {0}.
        /// </summary>
        public static string Log_DiscoverLanguages_Failed_Format {
            get {
                return ResourceManager.GetString("Log_DiscoverLanguages_Failed_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при обнаружении поддерживаемых языков..
        /// </summary>
        public static string Log_DiscoveryFailed {
            get {
                return ResourceManager.GetString("Log_DiscoveryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавлена резервная культура &quot;Русский&quot;, так как не удалось определить другие языки..
        /// </summary>
        public static string Log_FallbackCultureAdded {
            get {
                return ResourceManager.GetString("Log_FallbackCultureAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завершение работы приложения. Сброс буферов лога....
        /// </summary>
        public static string Log_FlushingLogs {
            get {
                return ResourceManager.GetString("Log_FlushingLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обнаружено {0} поддерживаемых языков: {1}.
        /// </summary>
        public static string Log_FoundLanguagesResult {
            get {
                return ResourceManager.GetString("Log_FoundLanguagesResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обнаружен нейтральный язык &apos;{0}&apos; из атрибута сборки..
        /// </summary>
        public static string Log_FoundNeutralLanguage {
            get {
                return ResourceManager.GetString("Log_FoundNeutralLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найдена сателлитная сборка для культуры &apos;{0}&apos;. .
        /// </summary>
        public static string Log_FoundSatelliteAssembly {
            get {
                return ResourceManager.GetString("Log_FoundSatelliteAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя директории &apos;{0}&apos; не является валидным кодом культуры..
        /// </summary>
        public static string Log_InvalidCultureDirectory {
            get {
                return ResourceManager.GetString("Log_InvalidCultureDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не выбран или не найден допустимый язык в настройках. Отображение окна выбора языка..
        /// </summary>
        public static string Log_LanguageSelectionNeeded {
            get {
                return ResourceManager.GetString("Log_LanguageSelectionNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка ввода/вывода при загрузке файла настроек &apos;{0}&apos;. Подробности: {1}.
        /// </summary>
        public static string Log_LoadSettings_IOException_Format {
            get {
                return ResourceManager.GetString("Log_LoadSettings_IOException_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка чтения файла настроек &apos;{0}&apos;: файл поврежден или имеет неверный формат. Подробности: {1}.
        /// </summary>
        public static string Log_LoadSettings_ReadFailed_Format {
            get {
                return ResourceManager.GetString("Log_LoadSettings_ReadFailed_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Непредвиденная ошибка при загрузке файла настроек &apos;{0}&apos;. Подробности: {1}.
        /// </summary>
        public static string Log_LoadSettings_Unexpected_Format {
            get {
                return ResourceManager.GetString("Log_LoadSettings_Unexpected_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Критическая ошибка инициализации MainWindow (ArgumentException): {0}.
        /// </summary>
        public static string Log_MainWindowInitArgumentError {
            get {
                return ResourceManager.GetString("Log_MainWindowInitArgumentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Критическая ошибка инициализации MainWindow: {0}.
        /// </summary>
        public static string Log_MainWindowInitError {
            get {
                return ResourceManager.GetString("Log_MainWindowInitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MainWindow успешно инициализировано (настройка ViewModel ожидается)..
        /// </summary>
        public static string Log_MainWindowInitialized {
            get {
                return ResourceManager.GetString("Log_MainWindowInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инициализация MainWindow..
        /// </summary>
        public static string Log_MainWindowInitializing {
            get {
                return ResourceManager.GetString("Log_MainWindowInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка завершить работу приложения из-за критической ошибки инициализации..
        /// </summary>
        public static string Log_MainWindowShutdownAttempt {
            get {
                return ResourceManager.GetString("Log_MainWindowShutdownAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Временный объект Puzzle создан для тестирования..
        /// </summary>
        public static string Log_MainWindowTempPuzzle {
            get {
                return ResourceManager.GetString("Log_MainWindowTempPuzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поддерживаемые языки не найдены автоматически. Попытка добавить резервные..
        /// </summary>
        public static string Log_NoLanguagesFound_AddingFallbacks {
            get {
                return ResourceManager.GetString("Log_NoLanguagesFound_AddingFallbacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось сохранить настройку выбранного языка..
        /// </summary>
        public static string Log_SaveLanguageSettingFailed {
            get {
                return ResourceManager.GetString("Log_SaveLanguageSettingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось сохранить настройки: директория для файла &apos;{0}&apos; не найдена..
        /// </summary>
        public static string Log_SaveSettings_DirectoryNotFound_Format {
            get {
                return ResourceManager.GetString("Log_SaveSettings_DirectoryNotFound_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка ввода/вывода при сохранении файла настроек &apos;{0}&apos;. Подробности: {1}.
        /// </summary>
        public static string Log_SaveSettings_IOException_Format {
            get {
                return ResourceManager.GetString("Log_SaveSettings_IOException_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет прав для сохранения настроек в файл &apos;{0}&apos;..
        /// </summary>
        public static string Log_SaveSettings_Unauthorized_Format {
            get {
                return ResourceManager.GetString("Log_SaveSettings_Unauthorized_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Непредвиденная ошибка при сохранении файла настроек &apos;{0}&apos;. Подробности: {1}.
        /// </summary>
        public static string Log_SaveSettings_Unexpected_Format {
            get {
                return ResourceManager.GetString("Log_SaveSettings_Unexpected_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл настроек &apos;{0}&apos; был удален..
        /// </summary>
        public static string Log_SettingsFileDeleted {
            get {
                return ResourceManager.GetString("Log_SettingsFileDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось удалить файл настроек &apos;{0}&apos;. Ошибка игнорируется..
        /// </summary>
        public static string Log_SettingsFileDeleteFailed {
            get {
                return ResourceManager.GetString("Log_SettingsFileDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки загружены из файла &apos;{0}&apos;..
        /// </summary>
        public static string Log_SettingsLoaded {
            get {
                return ResourceManager.GetString("Log_SettingsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки успешно сохранены в файл &apos;{0}&apos;..
        /// </summary>
        public static string Log_SettingsSaved {
            get {
                return ResourceManager.GetString("Log_SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Системная культура &quot;{0}&quot; добавлена в список..
        /// </summary>
        public static string Log_SystemCultureAdded {
            get {
                return ResourceManager.GetString("Log_SystemCultureAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось получить или добавить системную UI культуру как резервную..
        /// </summary>
        public static string Log_SystemCultureAddFailed {
            get {
                return ResourceManager.GetString("Log_SystemCultureAddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось определить системную культуру..
        /// </summary>
        public static string Log_SystemCultureDiscoveryFailed {
            get {
                return ResourceManager.GetString("Log_SystemCultureDiscoveryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необработанное исключение в AppDomain. Завершение: {0}.
        /// </summary>
        public static string Log_UnhandledExceptionAppDomain {
            get {
                return ResourceManager.GetString("Log_UnhandledExceptionAppDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необработанное исключение в AppDomain, объект исключения отсутствует. Завершение: {0}.
        /// </summary>
        public static string Log_UnhandledExceptionAppDomain_NoException {
            get {
                return ResourceManager.GetString("Log_UnhandledExceptionAppDomain_NoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необработанное исключение в Dispatcher..
        /// </summary>
        public static string Log_UnhandledExceptionDispatcher {
            get {
                return ResourceManager.GetString("Log_UnhandledExceptionDispatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь закрыл окно выбора языка или выбор не сделан. Используется первый доступный язык: {0}.
        /// </summary>
        public static string Log_UserClosedLanguageSelection {
            get {
                return ResourceManager.GetString("Log_UserClosedLanguageSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь выбрал язык: {0}.
        /// </summary>
        public static string Log_UserSelectedLanguage {
            get {
                return ResourceManager.GetString("Log_UserSelectedLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле Чудес.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
    }
}
