//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Field_of_Wonders.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Field_of_Wonders.Localization.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ответ не может быть пустым..
        /// </summary>
        public static string Error_AnswerCannotBeEmpty {
            get {
                return ResourceManager.GetString("Error_AnswerCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбранный язык &apos;{0}&apos; не найден ({1}).\nБудет использован язык по умолчанию..
        /// </summary>
        public static string Error_ApplyCulture_NotFound_Format {
            get {
                return ResourceManager.GetString("Error_ApplyCulture_NotFound_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка установки языка.
        /// </summary>
        public static string Error_ApplyCulture_Title {
            get {
                return ResourceManager.GetString("Error_ApplyCulture_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла непредвиденная ошибка при установке языка:\n{0}.
        /// </summary>
        public static string Error_ApplyCulture_Unexpected_Format {
            get {
                return ResourceManager.GetString("Error_ApplyCulture_Unexpected_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Критическая ошибка: Не удалось установить ни один из доступных языков. Приложение будет закрыто..
        /// </summary>
        public static string Error_Critical_CannotSetAnyLanguage {
            get {
                return ResourceManager.GetString("Error_Critical_CannotSetAnyLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось обнаружить поддерживаемые языки. Приложение будет закрыто..
        /// </summary>
        public static string Error_Critical_NoLanguagesFound {
            get {
                return ResourceManager.GetString("Error_Critical_NoLanguagesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Критическая ошибка.
        /// </summary>
        public static string Error_Critical_Title {
            get {
                return ResourceManager.GetString("Error_Critical_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка инициализации данных игры:\n{0}.
        /// </summary>
        public static string Error_DataInitializationFailed_Format {
            get {
                return ResourceManager.GetString("Error_DataInitializationFailed_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла ошибка при автоматическом определении языков:\n{0}\n\nБудет использован язык по умолчанию..
        /// </summary>
        public static string Error_DiscoverLanguages_Failed_Format {
            get {
                return ResourceManager.GetString("Error_DiscoverLanguages_Failed_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка определения языков.
        /// </summary>
        public static string Error_DiscoverLanguages_Title {
            get {
                return ResourceManager.GetString("Error_DiscoverLanguages_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка чтения файла настроек &apos;{0}&apos;:\n{1}\n\nПроверьте права доступа к папке приложения..
        /// </summary>
        public static string Error_LoadSettings_IOException_Format {
            get {
                return ResourceManager.GetString("Error_LoadSettings_IOException_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при чтении файла настроек &apos;{0}&apos;:\n{1}\n\nФайл будет удален. При следующем запуске потребуется выбрать язык..
        /// </summary>
        public static string Error_LoadSettings_ReadFailed_Format {
            get {
                return ResourceManager.GetString("Error_LoadSettings_ReadFailed_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка загрузки настроек.
        /// </summary>
        public static string Error_LoadSettings_Title {
            get {
                return ResourceManager.GetString("Error_LoadSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Непредвиденная ошибка при загрузке настроек из &apos;{0}&apos;:\n{1}\n\nФайл будет удален. При следующем запуске потребуется выбрать язык..
        /// </summary>
        public static string Error_LoadSettings_Unexpected_Format {
            get {
                return ResourceManager.GetString("Error_LoadSettings_Unexpected_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вопрос не может быть пустым..
        /// </summary>
        public static string Error_QuestionCannotBeEmpty {
            get {
                return ResourceManager.GetString("Error_QuestionCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось сохранить настройки.\nНе удалось определить директорию для файла настроек: {0}.
        /// </summary>
        public static string Error_SaveSettings_DirectoryNotFound_Format {
            get {
                return ResourceManager.GetString("Error_SaveSettings_DirectoryNotFound_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла ошибка при записи файла настроек &apos;{0}&apos;:\n{1}.
        /// </summary>
        public static string Error_SaveSettings_IOException_Format {
            get {
                return ResourceManager.GetString("Error_SaveSettings_IOException_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка сохранения настроек.
        /// </summary>
        public static string Error_SaveSettings_Title {
            get {
                return ResourceManager.GetString("Error_SaveSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось сохранить настройки.\nОтказано в доступе к файлу:\n{0}\n\nПроверьте права на запись..
        /// </summary>
        public static string Error_SaveSettings_Unauthorized_Format {
            get {
                return ResourceManager.GetString("Error_SaveSettings_Unauthorized_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла непредвиденная ошибка при сохранении настроек:\n{0}.
        /// </summary>
        public static string Error_SaveSettings_Unexpected_Format {
            get {
                return ResourceManager.GetString("Error_SaveSettings_Unexpected_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Непредвиденная ошибка при инициализации игры:\n{0}.
        /// </summary>
        public static string Error_UnexpectedInitializationFailed_Format {
            get {
                return ResourceManager.GetString("Error_UnexpectedInitializationFailed_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запуск приложения. Инициализация службы логирования..
        /// </summary>
        public static string Log_AppStarting {
            get {
                return ResourceManager.GetString("Log_AppStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завершение работы приложения. Сброс буферов лога....
        /// </summary>
        public static string Log_FlushingLogs {
            get {
                return ResourceManager.GetString("Log_FlushingLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле Чудес.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
    }
}
